### ISSUE TITLE
Slow Loading Time

### ISSUE THREAD

**Issue by malaverdiere** [bmc/classutil#16]
I am loading from the JDK, so that's a lot of classes. Using ClassFinder, it takes 20+ seconds. I am guessing that since there is a lot of IO involved, it would be possible to parallelize it.

Is it something that would be beneficial, or you already did some experiments and showed that it wasn't?

**Comment by bmc** [comment]
Finally got around to testing this one. With the latest release (1.0.7), I loaded a class path that contained both the Scala runtime jar and the JDK 1.8 runtime jar, a total of more than 25,000 class. `ClassFinder.getClasses.toVector` took 1.2 seconds on my MacBook Pro (2 cores, 16GB RAM).

I'm closing this one as fixed.
