### ISSUE TITLE
No annotation info in ClassInfo

### ISSUE THREAD

**Issue by ruippeixotog** [bmc/classutil#17]
There seems to be no support for retrieving the runtime Java annotations of a class. In some situations it is useful to get all classes marked with a certain annotation together with the annotation parameters.

From what I understood in a quick tour around the source code, it would be a matter of overriding `visitAnnotation` in your `ClassVisitor` and adding a new `annotations` field in `ClassInfoImpl`, wouldn't it?

**Comment by bmc** [comment]
Fixed in version 1.0.6
